name: "CI"

on:
  pull_request:
  push:
    branches:
    - master

env:
  CF_API_KEY: ${{ secrets.CURSEFORGE_APIKEY}}

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        era: [bcc, classic, retail]
    steps:
      - name: Install 'luarocks'
        run: sudo apt-get install luarocks
      - name: Install 'luacheck'
        run: luarocks install --local luacheck
      - uses: actions/checkout@v2
      - uses: BigWigsMods/packager@v1
        name: BuildPackage
        with:
          args: -g ${{ matrix.era }} -m .pkgmeta -d -L
      - uses: actions/upload-artifact@v2
        with:
          name: AddonPackages
          path: './.release/*.zip'
          if-no-files-found: error